// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbLAWOzl0Kwv97qcaGuSp9ymRmrV39hlE',
    appId: '1:385800409693:web:5c92bc5d650647c870f3b4',
    messagingSenderId: '385800409693',
    projectId: 'ble-street-lights-project',
    authDomain: 'ble-street-lights-project.firebaseapp.com',
    storageBucket: 'ble-street-lights-project.appspot.com',
    measurementId: 'G-53RJ6TV8FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXVlkcxxHGuI7Bq2ToSE7lDAvatnSWTNM',
    appId: '1:385800409693:android:bb87cd87a1cbd7cd70f3b4',
    messagingSenderId: '385800409693',
    projectId: 'ble-street-lights-project',
    storageBucket: 'ble-street-lights-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC112vXVKIFVVj1zPji8666sO1Ufl5j9nQ',
    appId: '1:385800409693:ios:48e0e51584a1376570f3b4',
    messagingSenderId: '385800409693',
    projectId: 'ble-street-lights-project',
    storageBucket: 'ble-street-lights-project.appspot.com',
    iosClientId: '385800409693-55vp1eh87m1ovlvmmhnt00aktnadtcjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.bleStreetLights',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC112vXVKIFVVj1zPji8666sO1Ufl5j9nQ',
    appId: '1:385800409693:ios:48e0e51584a1376570f3b4',
    messagingSenderId: '385800409693',
    projectId: 'ble-street-lights-project',
    storageBucket: 'ble-street-lights-project.appspot.com',
    iosClientId: '385800409693-55vp1eh87m1ovlvmmhnt00aktnadtcjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.bleStreetLights',
  );
}
